kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: build-ce-console-pipeline-run-
spec:
  pipelineRef:
    name: build-ce-console-pipeline
  params:
    - name: "git-url"
      value: "https://github.com/pittar-integration/cloudevent-console.git"
    - name: "git-revision"
      value: "main"
    - name: "app-name"
      value: "camel-timer-cloudevents"
    - name: "namespace"
      value: "cetest"
  workspaces:
    - name: build-workspace
      persistentVolumeClaim:
        claimName: build-ce-console-workspace
    - name: maven-settings
      emptyDir: {}